require("components.syntax_parser") -- 语法分析
require("components.indent_guides") -- 缩进参考线
require("components.auto_pairs") -- 自动补全括号
require("components.comment") -- 注释
require("components.git_signs") -- git集成
require("components.project_manager") -- 项目管理
require("components.file_tree") -- 文件树
require("components.tab_bar") -- 标签栏
require("components.status_bar") -- 状态栏
require("components.fuzzy_finder") -- 模糊查找
require("components.start_screen") -- 启动页
